name: painless_oauth_web
description: A painless_oauth implemention for the web
version: 0.0.1
author:
homepage:

flutter:
  assets:
    - capturer/oauth_callback_capturer_service_worker.js
  plugin:
    implements: painless_oauth
    platforms:
      web:
        pluginClass: PainlessOAuthPlugin
        fileName: painless_oauth_web.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  painless_oauth_interface:
    path: ../painless_oauth_interface
  # todo distribute a copy of the license of the service worker api (caused by BSD 3-Clause "New" or "Revised" License)
  service_worker: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

