name: painless_oauth
description: An OAuth library that tries to be painless.
version: 0.0.1
author: Lukas Meili
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:


dependencies:
  flutter:
    sdk: flutter
  painless_oauth_interface:
    path: ../painless_oauth_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
