name: painless_oauth
description: An OAuth library that tries to be painless.
version: 0.0.1
author: Lukas Meili
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: painless_oauth_web

dependencies:
  flutter:
    sdk: flutter
  painless_oauth_interface:
    path: ../painless_oauth_interface
  painless_oauth_web:
    path: ../painless_oauth_web

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
