# This is a basic workflow to help you get started with Actions

name: Unit tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  abstract-plugin-unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.1
      with:
        channel: 'stable' 
    
    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: painless_oauth
    
    - name: Run unit tests
      run: flutter test
      working-directory: painless_oauth
  
  web-implementation-unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.1
      with:
        channel: 'dev' 
    
    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: painless_oauth_web
    
    - name: Run unit tests
      run: flutter test
      working-directory: painless_oauth_web
      
